### ISSUE TITLE
Connecting printer failed: 1

### ISSUE THREAD

**Issue by pilz97** [MarkChu/cordova-plugin-epson-epos2-tm-p20#1]
Hi,

i have an Epson TM p20.
I am using an Android Device which a paired with the printer via bluetooth.

To detect the paired devices i use an external cordova plugin, which returns me the bluetooth name + address.
When the user selects an epson printer i want to use this plugin so i am calling: 
`cordova.epos2.connectPrinter(printer.address, printer.name)`

But every time this error is thrown by the plugin:
Error: Error 0x00012: Connecting printer failed: 1
    at plugin.js:43
    at Object.callbackFromNative (cordova.js:289)
    at <anonymous>:1:9

Any Idea?

**Comment by MarkChu** [comment]
Below is my code example, I hope it can help you.

`      var my_device = 'AB:CC:DD:EE:FF:00'`
`      var my_model = 'TM-P20'`
`      var device = 'BT:' + my_device `
`      var model = my_model `
`      cordova.epos2.connectPrinter(device, model)`
`        .then(function () {`
`          /**`
`           * Send text to the connected printer`
`           *`
`           * Can be called multiple times for additional text lines.`
`           * Set `terminate` to True in order to complete the print job.`
`           *`
`           * @param {String|Array} data List of strings to be printed as text. Use '\n' to feed paper for one line.`
`           * @param {Number} [textFont=0] Select font: 0 = Font A, 1 = Font B, 2 = Font C, 3 = Font D, 4 = Font E`
`           * @param {Number} [textSize=1] Define text size (1..8)`
`           * @param {Number} [textAlign=0] Define text alignment: 0 = left, 1 = center, 2 = right`
`           * @param {Boolean} [terminate=false] Send additional line feeds an a "cut" command to complete the print`
`           * @param {Function} [successCallback]`
`           * @param {Function} [errorCallback]`
`           * @return {Promise} resolving on success, rejecting on error`
`           */`
`          return cordova.epos2.printText([`
`            'test-line1\n'`
`          ], 0, 2, 1, false)`
`        })`
`        .then(function () {`
`          return cordova.epos2.printText([`
`            '\n'`
`          ], 0, 1, 0, false)`
`        })`
`        .then(function () {`
`          return cordova.epos2.printBarCode128('RP202006050012', 2, 0, 2, 70, false)`
`        })`
`        .then(function () {`
`          return cordova.epos2.printText([`
`            'test-line2\n'`
`          ], 0, 1, 0, false)`
`        })`
`        .then(function () {`
`          return cordova.epos2.disconnectPrinter()`
`            .catch(function () {`
`              /* ignore disconnect errors */`
`            })`
`        })`
`        .then(function () {`
`          console.log('Printing complete.')`
`        })`
`        .catch(function (err) {`
`          console.error('Printing failed', err)`
`        })`
`    }`

**Comment by NiklasMerz** [comment]
From my experience it helps to pair the printer with the Epson TM Utilty app first.
